config/routes.rb
Rails.application.routes.draw do
  
  

  root   'static_pages#home'
  get    '/signup',    to: 'users#new'
  get    '/all_users', to: 'users#everybody'
  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'
  
  resources :users, except: [:new]
  resources :categories, only: [:show,:index]
  resources :videos do
    collection do
      post :category
    end
  end
 
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_many :videos, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :name ,presence: true,length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email,presence: true,length: { maximum: 255 },
                                  format: {with: VALID_EMAIL_REGEX},
                                  uniqueness: {case_sensitive: false}
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,100}+\z/i                               
  validates :password,presence: true,length: {minimum:8},
                                     format: {with: VALID_PASSWORD_REGEX},
                                     allow_nil: true
  has_secure_password
  
  #渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
   # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  #永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest , User.digest(remember_token))
  end
  
  #渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
      return false if remember_digest.nil?
     BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  #ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  
  
  #ユーザー登録フォームの表示
  def new
    @user = User.new
  end
  
  #ユーザー登録
  def create
    @user = User.new(user_params)
    if @user.save
      #成功時
      log_in @user
      flash[:success] = "登録が完了しました！"
      redirect_to @user
    else
      #失敗時
      render "new"
    end
  end
  
  #ユーザー画面
  def show
    @user = User.find_by(id: params[:id])
    @videos = @user.videos
    end
  
  #すべてのユーザー(adminのみが見れる)
  def everybody
    @user = User.all if admin_user?
  end
  
  #ユーザー情報編集画面の表示
  def edit
    @user = User.find_by(id: params[:id])
  end
  
  #ユーザー情報編集
  def update
    @user =User.find_by(id:params[:id])
    if @user.update_attributes(user_params)
      #編集に成功した時
      flash[:success] = "編集しました"
      redirect_to @user
    else
      #編集に失敗した時
      render "edit"
    end
  end
  
  def destroy
  User.find(params[:id]).destroy
    flash[:success] = "ユーザーは削除されました"
    redirect_to root_path
  end
  
  #ストロングパラメータ
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  
  #http://youtube.com/watch?v=〇〇〇〇 この〇〇〇〇の部分を取り出す
  def create_video_id(url)
    url.gsub(/https:\/\/www.youtube.com\/watch\?v=(\w+)/){"#{$1}"} 
  end
end

app/views/users/_user_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(object) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :name,"名前" %>
      <%= f.text_field :name,class: "form-control" %>

      <%= f.label :email,"メールアドレス" %>
      <%= f.email_field :email,class: "form-control" %>

      <%= f.label :password,"パスワード(英数字を組み合わせて8文字以上)" %>
      <%= f.password_field :password,class: "form-control" %>

      <%= f.label :password_confirmation, "パスワードの再入力" %>
      <%= f.password_field :password_confirmation,class: "form-control" %>

      <%= f.submit class: "btn btn-primary" %>
    <% end %>
    
    <p class="deleting">
      <%= link_to "アカウントの削除" ,object,
      method: :delete,data: {confirm: "本当に削除してもよろしいですか？"} %>
    </p>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title,'会員情報編集')%>
  <h1>会員情報編集</h1>
  <%= render "user_form", object: @user%>

app/views/users/everybody.html.erb
<%provide(:title,"すべてのユーザー")%>
<div class="container">
  <div class="row">
    <section class="col-md-10">
      <% @user.each do |u| %>
      <%= link_to "動画一覧", video_path(u) %> | 
      <%= link_to "編集",edit_user_path(u) %> | 
      <% if not admin_user?(u)%>
      <%= link_to "アカウント削除",u, method: :delete,
                                      data: {confirm: "本当に削除してもよろしいですか？"}%>
      <%end%>
      <%=render "shared/profile",object: u %>
      <hr>
      <%end%>
    </section>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, '会員登録') %>
<div class="container">
<h1>会員登録</h1>
<p style="text-align:center;">ユーザーは自分のyoutube動画を投稿することができます。</p>

<%= render "user_form",object: @user %>

</div>

app/views/users/show.html.erb
<% provide(:title, "#{@user.name}のプロフィール") %>


  <div class="col-md-6 col-md-offset-3">
    <section>
    <p>
      <span><%= @user.name %></span>
      <%if logged_in? %>
        <% if @user == current_user || admin_user? %>
        <%= link_to "編集する",edit_user_path(@user) %>
        <%end%>
      <%end%>
    </p>
    </section>
  </div>
</div>

<hr>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <section>
    <p><%= render "shared/youtube" %></p>
    </section>
  </div>
</div>