config/routes.rb
Rails.application.routes.draw do
  
  

  root   'static_pages#home'
  get    '/signup',    to: 'users#new'
  get    '/all_users', to: 'users#everybody'
  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'
  
  resources :users, except: [:new]
  resources :categories, only: [:show,:index]
  resources :videos do
    collection do
      post :category
    end
  end
 
end

app/models/video.rb
class Video < ApplicationRecord
  #acts_as_nested_set
  belongs_to :user
  has_many :video_category_relationships,
                                         dependent: :destroy
  has_many :categories, through: :video_category_relationships
  
  default_scope -> { order(created_at: :desc) }
  validates :user_id,presence:true
  validates :title,presence:true,length: {maximum:50}
  validates :description ,length: {maximum:300}
  #urlの正規表現 正しいかチェックの必要あり
  VALID_URL_REGEX = /\A(https:\/\/www.youtube.com\/watch\?v=)([-\w]{11})\z/
  validates :url,presence:true,format: {with: VALID_URL_REGEX}
  
  
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :destroy]
  
  #個別動画
  def show
    @videos = []
    @videos[0] = Video.find_by(id: params[:id])
   
  end
  
  
  #投稿画面の表示
  def new
    @video = Video.new
    set_categories(@video)
  end
  
  #投稿
  def create
    @video = current_user.videos.build(video_params)
    if @video.save
      #投稿成功時
      flash[:success] = "投稿に成功しました！"
      redirect_to user_path(current_user)
    else
      #投稿失敗時
      set_categories(@video)
      render "new"
    end
  end
  
  
  #動画編集画面
  def edit
    @video = Video.find_by(id: params[:id])
    set_categories(@video)
  end
  
  #動画編集
  def update
    @video = Video.find_by(id: params[:id])
    if @video.update_attributes(video_params)
      #編集に成功
      flash[:success] = "編集しました"
      redirect_to video_path @video.id
    else
      #編集に失敗
      set_categories(@video)
      render "edit"
    end  
  end
  
  
  #投稿の削除
  def destroy
    
    video =Video.find(params[:id])
    video.destroy
    flash[:success] = "動画は削除されました"
    redirect_to video_path video.user_id
  end
  
  def category
    @parent_category = Category.find(params[:category_id])
  end
  
  
  private
  
    def video_params
      params.require(:video).permit(:title, :description , :url, category_ids: [])
    end
    
    #カテゴリ情報をDBからとりだす
    def set_categories(video)
    @parent_categories = Category.where(parent_id: nil)
    @parent_category = Category.find_by(id: video.category_ids[0]) 
    @parent_category_id = @parent_category ? @parent_category.id : nil
    @child_category = Category.find_by(id: video.category_ids[1])
    end 
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_video_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@video) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :title,"動画タイトル(必須)" %>
      <%= f.text_field :title, class: "form-control" %>

      <%= f.label :description,"概要(300文字以内)" %>
      <%= f.text_area :description,class: "form-control" %>

      <%= f.label :url,"動画URL(必須)" %>
      <%= f.text_field :url,placeholder: "https://www.youtube.com/watch?v=sample",class: "form-control" %>
      
      <%= label_tag :video_category , "カテゴリー" %>
      <%= select_tag "video[category_ids][]", options_from_collection_for_select(@parent_categories, :id, :category,{ selected: @parent_category_id}) ,
      { class: "form-control" , id: "video_category" } %>
     
      <div id="children">
        <% if @child_category %>
          <%= label_tag :video_sub_category , "サブカテゴリー" %>
          <%= select_tag "video[category_ids][]", options_from_collection_for_select(@parent_category.children, :id, :category,selected: @child_category.id) , { class: "form-control" , id: "video_sub_category"} %>
        <% end %>
      </div>     
    
 
      <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<script>
$(function() {
    $('#video_category').change(function() {
      $.post({
        url: "<%= category_videos_path %>",
        data: { category_id: $('#video_category').has('option:selected').val() , format: "js" }
      });
    });
  });
</script>

app/views/videos/category.js.erb
<% if @parent_category.children.present? %>
$('#children').html('<%= j(label_tag :video_sub_category , "テーマ") %><%= j(select_tag "video[category_ids][]", options_from_collection_for_select(@parent_category.children, :id, :category),{ class: "form-control" , id: "video_sub_category"})%>');
<% else %>
$('#children').html('');
<% end %>

app/views/videos/edit.html.erb
<%provide(:title,"動画の編集")%>

  <%= render "video_form"%>

app/views/videos/new.html.erb
<% provide(:title, '投稿') %>
<h1>動画を投稿する</h1>

<div class="container">
  <%= render "video_form"%>  
</div>

app/views/videos/show.html.erb
<%provide(:title, "Mytube")%>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <section>
        <%= render "shared/youtube"%>
        <%if logged_in? %>
          <%if current_user == @videos[0].user || admin_user? %>
          <%= link_to "一覧ページへ戻る", user_path(current_user) %>
          <%end%>
        <%end%>
    </section>
   </div>
  </div>