config/routes.rb
Rails.application.routes.draw do
  
  

  root   'static_pages#home'
  get    '/signup',    to: 'users#new'
  get    '/all_users', to: 'users#everybody'
  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'
  
  resources :users, except: [:new]
  resources :categories, only: [:show,:index]
  resources :videos do
    collection do
      post :category
    end
  end
 
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_nested_set
  has_many :video_category_relationships,dependent: :destroy
  has_many :videos, through: :video_category_relationships
  validates :category ,presence: true
  
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  #カテゴリの動画すべてとそのカテゴリのテーマをすべて表示
  def show
    #カテゴリー動画をすべて取り出す
    @videos = Category.find_by(id: params[:id]).videos
    #テーマをすべて取り出す。
    @themes = Category.where(parent_id: params[:id] )
  end
  
  #それぞれのテーマの動画を表示
  def index
    #動画を取り出す
    theme = Category.find_by(id: params[:theme])
    @videos = theme.videos.reorder(score: :desc)
  end
  
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_ranking.html.erb
<% @videos.each_with_index do |video , cnt| %>
      <p>
        カテゴリ :
        <% video.categories.each_with_index do |category,count|%>
        <%=" , " if count > 0  %>
        <%=category.category%>
        <%end%>
      </p>
      <h3>第<%= cnt + 1 %>位：　<%= video.title %></h3>
      <div class="youtube-container">        
        <iframe src="https://www.youtube.com/embed/<%= create_video_id video.url %>" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
      </div>
      <p>シェア数: <%= video.score%></p>
      <p><%= video.description%></p>
      
      <% if logged_in? %>
        <%if current_user == video.user || admin_user? %>
        <%= link_to "編集する",edit_video_path(video)%> | 
        <%= link_to "削除する",video_path(video),method: :delete,
                             data: {confirm: "本当に削除してもよろしいですか？"} %>
        <%end%>
      <%end%>
      <hr>
    <%end%>

app/views/categories/index.html.erb
<%provide(:title, "テーマ")%>
  <div class="row">
    <div class="col-xs-9">
    <section>
    <% if @videos.count > 0%>
      <%= render "ranking"%>
    <%else%>
      <p>まだ動画が投稿されていません。</p>
    <%end%>
   </section>
   </div>
  </div>

app/views/categories/show.html.erb
<div class="row">
    <div class="col-md-6">
    <section>
      <%= render "shared/youtube" %>
    </section>
    </div>
    
  <div class="col-md-5 col-md-offset-1">
    <p>テーマ一覧</p>  
    <ul class="list-theme">
      <% @themes.each do |theme|%>
      <li><%= link_to theme.category, action: "index",theme: theme.id %></li>
      <%end%>
    </ul>
  </div>
  
</div>