config/routes.rb
Rails.application.routes.draw do
  
  

  root   'static_pages#home'
  get    '/signup',    to: 'users#new'
  get    '/all_users', to: 'users#everybody'
  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'
  
  resources :users, except: [:new]
  resources :categories, only: [:show,:index]
  resources :videos do
    collection do
      post :category
    end
  end
 
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    サイト名 all rights reserved.
  </small>
  <nav>
    <ul> 
      <li><%= link_to "ホーム",   root_path %></li>
      <%if logged_in?%>
      <li><%= link_to "投稿する", new_video_path %></li>
      <li><%= link_to "ログアウト", logout_path, method: "delete" %></li>
      <%else%>
      <li><%= link_to "ログイン", login_path %></li>
      <li><%= link_to "会員登録", signup_path %></li>
      <%end%>
      <li><%= link_to "お問合せ", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-default">
    <div class="container">
      <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
     <%= link_to "Youtube App", root_path, id: "logo" %>
    </div>
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <nav>
      <ul class="nav navbar-nav navbar-right">
    <li><%= link_to "ホーム", root_path %></li>
    <% if logged_in? %>
      <%if admin_user?%>  
        <li><%= link_to "すべてのユーザー", all_users_path %></li>
      <%end%>
      <li><%= link_to "投稿する", new_video_path %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          アカウント <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "プロフィール", current_user %></li>
          <li class="divider"></li>
          <li>
            <%= link_to "ログアウト", logout_path, method: "delete" %>
          </li>
        </ul>
      </li>
    <% else %>
      <li><%= link_to "会員登録",   signup_path %></li>
      <li><%= link_to "ログイン",   login_path %></li>
    <% end %>
      <li><%= link_to "お問合せ", '#' %></li>
      </ul>
    </nav>
    </div>
    </div>
  </header>
 
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <%= render "layouts/header" %>
      <div class="container">
        <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      <%= yield %>
      <%= render "layouts/footer"%>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>